/**
 * @file cancel_verify_code.js
 * @author scott@converse.ai
 * @description Cancel an active verification request
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status = require('@converseai/plugins-sdk').Status;
const ModuleResponse = require('@converseai/plugins-sdk').Payloads.ModuleResponse;
const Utils = require('../lib/utils.js');

module.exports = function cancel_verify_code(app, body) {

  var registrationData = body.payload.registrationData;
  var moduleParam = body.payload.moduleParam;

  var requestId = moduleParam.request_id;
  if (!requestId) {
    var response = new ModuleResponse();
    response.setError({
      httpStatus: 400,
      code: "REQUIRED_PARAMS_UNDEFINED",
      description: "Required parameter 'Request Id' is undefined."
    });
    app.send(Status.FAIL, response);
    return;
  }

  Utils.cancelVerifyCode(registrationData, requestId, 3, function(ok, result) {
    if (!ok) {
      console.error(result);
      var response = new ModuleResponse();
      response.setError({
        httpStatus: 500,
        code: "FUNCTION_FAILED",
        description: result,
      });
      app.send(Status.FAIL, response);
      return;
    }

    var response = new ModuleResponse();
    response.setValue(result);
    app.send(Status.SUCCESS, response);
  });

};